#!/usr/bin/env python3
"""Add the deployment peers and per-process CURVE identities to a config set.

The protocol keys are intentionally left untouched: for distributed runs they
are generated by the target-architecture image before this script is called.
"""

import argparse
import json
import uuid
from pathlib import Path

import zmq


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config-dir", required=True, type=Path)
    parser.add_argument("--ip-file", required=True, type=Path)
    parser.add_argument("--n", required=True, type=int)
    parser.add_argument("--layers", required=True, type=int)
    args = parser.parse_args()

    ips = [line.strip() for line in args.ip_file.read_text().splitlines() if line.strip()]
    if len(ips) < args.n:
        raise ValueError(f"need {args.n} peer IPs, found {len(ips)}")

    process_count = args.n * args.layers
    paths = [args.config_dir / f"local.{index}.json" for index in range(process_count)]
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"missing config files: {missing}")

    peers = [
        f"{ip}:{7001 + layer}"
        for layer in range(args.layers)
        for ip in ips[: args.n]
    ]
    curve_keypairs = [zmq.curve_keypair() for _ in range(process_count)]
    curve_public_keys = [public.decode("ascii") for public, _ in curve_keypairs]

    first = json.loads(paths[0].read_text())
    run_id = first.get("extra", {}).get("run_id") or uuid.uuid4().hex
    curve_zap_domain = f"continuum-{run_id}"

    for global_id, path in enumerate(paths):
        config = json.loads(path.read_text())
        config["peers"] = peers
        extra = config.setdefault("extra", {})
        extra.update(
            {
                "run_id": run_id,
                "curve_public_key": curve_public_keys[global_id],
                "curve_secret_key": curve_keypairs[global_id][1].decode("ascii"),
                "curve_public_keys": curve_public_keys,
                "curve_zap_domain": curve_zap_domain,
            }
        )
        path.write_text(json.dumps(config, indent=4, ensure_ascii=False) + "\n")

    print(f"Added deployment peers and CURVE identities to {process_count} configs")


if __name__ == "__main__":
    main()
